Select * FROM AMAZONE_BOOKS;

Select DISTINCT BUSINESS_DATE FROM AMAZONE_BOOKS;

UPSERT INTO AMAZONE_BOOKS (column1, column2, ...) VALUES (value1, value2, ...) ON 
CONFLICT (column) DO UPDATE SET column1 = value1, column2 = value2, ...;

UPSERT INTO AMAZONE_BOOKS (BOOK_ID, BOOK_TITLE, BOOK_AMOUNT, BOOK_AUTHOR, BOOK_RATING, BOOK_LINK, BUSINESS_DATE , FILE_DATE_PARTITION) 
VALUES (value1, value2, ...) ON 
CONFLICT (column) DO UPDATE SET column1 = value1, column2 = value2, ...;

MERGE INTO AMAZONE_BOOKS T1
  USING (SELECT * FROM AMAZONE_BOOKS_EXT WHERE FILE_DATE_PARTITION > 20240226 ) T2 ON T1.BOOK_ID = T2.BOOK_ID 
  WHEN MATCHED THEN UPDATE SET T1.BOOK_TITLE = T2.BOOK_TITLE,
                                T1.BOOK_AMOUNT = T2.BOOK_AMOUNT,
                                T1.BOOK_RATING = T2.BOOK_RATING, 
                                T1.BOOK_LINK = T2.BOOK_LINK,
                                T1.BUSINESS_DATE = T2.BUSINESS_DATE,
                                T1.FILE_DATE_PARTITION = T2.FILE_DATE_PARTITION
  WHEN NOT MATCHED THEN INSERT (BOOK_ID, BOOK_TITLE, BOOK_AMOUNT, BOOK_AUTHOR, BOOK_RATING, BOOK_LINK, BUSINESS_DATE , FILE_DATE_PARTITION)
  VALUES (T2.BOOK_ID, T2.BOOK_TITLE, T2.BOOK_AMOUNT, T2.BOOK_AUTHOR, T2.BOOK_RATING, T2.BOOK_LINK, T2.BUSINESS_DATE , T2.FILE_DATE_PARTITION);

SELECT count(*) FROM AMAZONE_BOOKS WHERE FILE_DATE_PARTITION > 20240229;
-- Out put => 45

DELETE FROM AMAZONE_BOOKS WHERE FILE_DATE_PARTITION > 20240229;

SELECT count(*) FROM AMAZONE_BOOKS_EXT;
-- 121

SELECT count(*) FROM AMAZONE_BOOKS;
-- 333

SELECT 
(SELECT count(*) FROM AMAZONE_BOOKS_EXT WHERE FILE_DATE_PARTITION = 20240301) as AMAZONE_BOOKS_EXT,
(SELECT count(*) FROM AMAZONE_BOOKS WHERE FILE_DATE_PARTITION = 20240301) as AMAZONE_BOOKS;

DELETE FROM  amazonebook_reviews T1 USING ( SELECT  BOOK_ID, REVIEWER_NAME, BUSINESS_DATE FROM amazonebook_reviews_ext t WHERE FILE_DATE_PARTITION > 20240301) T2 WHERE  T1.BOOK_ID = T2.BOOK_ID and T1.REVIEWER_NAME = T2.REVIEWER_NAME and T1.BUSINESS_DATE = T2.BUSINESS_DATE ;

DELETE FROM  amazone_books T1 USING ( SELECT  BOOK_ID FROM AMAZONE_BOOKS_EXT t WHERE FILE_DATE_PARTITION > 20240229 ) T2 WHERE  T1.BOOK_ID = T2.BOOK_ID ;

INSERT INTO amazone_books 
(SELECT BOOK_ID,BOOK_TITLE,BOOK_AMOUNT,BOOK_AUTHOR,BOOK_RATING,BOOK_LINK,BUSINESS_DATE,FILE_DATE_PARTITION FROM AMAZONE_BOOKS_EXT WHERE FILE_DATE_PARTITION > 20240229);


SELECT 
(SELECT count(*) FROM AMAZONE_BOOKS_EXT ) as AMAZONE_BOOKS_EXT,
(SELECT count(*) FROM AMAZONE_BOOKS) as AMAZONE_BOOKS;

SELECT 
(SELECT count(*) FROM AMAZONEBOOK_REVIEWS_EXT ) as AMAZONEBOOK_REVIEWS_EXT,
(SELECT count(*) FROM AMAZONEBOOK_REVIEWS) as AMAZONEBOOK_REVIEWS;

SELECT 
